export const AUTH_TOKEN_KEY = "uc_token";
export const EMAIL_MAX_LENGTH = 255;
export const FIELD_SKIPPED = "FIELD_SKIPPED";

export const SSO_URL = process.env.REACT_APP_UC_SSO_URL || "";
export const PROJECT_URL = process.env.REACT_APP_UC_SSO_PROJECT_URL || "";
export const UPLOADED_LOGO_BASE64_STORAGE_KEY = "logo_base64";
export const anotherTemplate = "anotherTemplate";
export const RASA_UPLOAD_COMPLETED = "Upload completed";
export const RASA_NO_LOGO = "Dont have project logo";
export const defaultProjectName = "project-name";
export enum ChatPagePostMessage {
  SET_LOCAL_STORAGE = "SET_LOCAL_STORAGE",
  HIDE_LIVE_CHAT = "HIDE_LIVE_CHAT",
  SHOW_LIVE_CHAT = "SHOW_LIVE_CHAT",
  SIGN_IN = "SIGN_IN",
  SEND_PROJECT_DATA = "SEND_PROJECT_DATA",
  OPEN_SIGN_IN_MODAL = "OPEN_SIGN_IN_MODAL",
  TOGGLE_TEMPLATE_MODAL = "TOGGLE_TEMPLATE_MODAL",
  SET_TEMPLATE_ID = "SET_TEMPLATE_ID",
  SET_USER_INFO = "SET_USER_INFO",
  OPEN_AI_TEMPLATE_BY_ID_MODAL = "OPEN_AI_TEMPLATE_BY_ID_MODAL",
  OPEN_AI_TEMPLATE_MODAL = "OPEN_AI_TEMPLATE_MODAL",
  SET_AI_TEMPLATE_ID = "SET_AI_TEMPLATE_ID",
  SET_AI_TEMPLATE_RANDOM_ID = "SET_AI_TEMPLATE_RANDOM_ID",
  OPEN_PAYMENT_MODAL = "OPEN_PAYMENT_MODAL",
  PAYMENT_DATA = "PAYMENT_DATA",
  PRODUCT_DESCRIPTION_SAVE = "PRODUCT_DESCRIPTION_SAVE",
  CHILD_READY = "CHILD_READY",
}
